version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:8080"
    secrets:
      - token_key_01
      - capx_rsa_key

secrets:
  token_key_01:
    file: ./token_key_01.pem
  capx_rsa_key:
    file: ./capx_rsa_key.pem
