version: "3.9"

services:
  web:
    build: .
    ports:
      - "80:8080"
        #    secrets:
        #- capx_private_rsa_key

        #secrets:
        #  capx_private_rsa_key:
        #    file: ./keys/private.pem
